### ISSUE TITLE
Not finished the backup

### ISSUE THREAD

**Issue by jyr** [jbt/campfire-archive#1]
After put the token via web, I have a error:

Fetching 2013-6-14 for room 559196 from campfire
Fetching 2013-6-15 for room 559196 from campfire
Fetching 2013-6-16 for room 559196 from campfire
Fetching 2013-6-17 for room 559196 from campfire

/opt/boxen/nodenv/versions/v0.10.13/lib/node_modules/campfire-archive/lib/CampfireArchiver.js:245
  transcript.messages.forEach(this.processTranscriptMessage.bind(this));
                      ^
TypeError: Cannot call method 'forEach' of undefined
    at CampfireArchiver.processTranscript (/opt/boxen/nodenv/versions/v0.10.13/lib/node_modules/campfire-archive/lib/CampfireArchiver.js:245:23)
    at null.<anonymous> (/opt/boxen/nodenv/versions/v0.10.13/lib/node_modules/campfire-archive/lib/CampfireArchiver.js:238:12)
    at /opt/boxen/nodenv/versions/v0.10.13/lib/node_modules/campfire-archive/lib/CampfireArchiver.js:209:13
    at Object.oncomplete (fs.js:107:15)

This is it a bug?

**Comment by colemanm** [comment]
Just tried this and ran into the same issue. Maybe something to do with the transcript data for the specific day?

**Comment by copiousfreetime** [comment]
I just got this, and it has to do with campfire throttling the data pull, from the last archive file pulled down...

```
% cat 2011-9-11.json
"You have exceeded 50 missing_useragent_header requests in a 10-second period. Please wait 10 seconds before retrying."
```

Sounds like setting  User-Agent header in the request will solve the issue.

**Comment by crogg** [comment]
This just gets you to the next level of throttling:

```
$ cat 2014-6-8.json
"You have exceeded 500 web requests in a 10-second period. Please wait 10 seconds before retrying."
```

**Comment by drkpxl** [comment]
Getting something similar.

/usr/local/lib/node_modules/campfire-archive/lib/CampfireArchiver.js:245
  transcript.messages.forEach(this.processTranscriptMessage.bind(this));
                     ^
TypeError: Cannot read property 'forEach' of undefined
    at CampfireArchiver.processTranscript (/usr/local/lib/node_modules/campfire-archive/lib/CampfireArchiver.js:245:22)
    at null.<anonymous> (/usr/local/lib/node_modules/campfire-archive/lib/CampfireArchiver.js:238:12)
    at /usr/local/lib/node_modules/campfire-archive/lib/CampfireArchiver.js:209:13
    at FSReqWrap.oncomplete (fs.js:95:15)

**Comment by senny** [comment]
Same for me.

**Comment by johngb** [comment]
Same problem here
